[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
log = "0.4.20"
merge = "0.1.0"
rand = "0.8.5"
serde =  { version = "1.0", features = ["derive"] }
transpose = "0.2.2"
